site_name: maplecroft
site_description: "The maplecroft technical test"
repo_url: https://github.com/maplecroft/maplecroft-tech-test
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/maplecroft">maplecroft</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
